### ISSUE TITLE
Security update suggestion

### ISSUE THREAD

**Issue by eosgameboy** [eoswindev/contract#1]
## Security update suggestion at `transfer` function in EOS

Recently, Hackers attack smart-contract with tricky and unexpected ideas.
That's why every developer should insert defense codes in smart-contract to block attacks.

Your codes seem to be using hooking 'transfer' function to start the game.
It is a good idea to check a `transfer` of `eosio.token` in the `first action` of `transaction`.

Hackers usually try to manipulate your contract through main-contract or their contract in sub-account. In this case, you may inspect the contract and `function action name` sent by the hacker by reading `action` of those function parsing `read_transaction`. In a normal case, the `transfer` of `eosio.token` will be read. in other cases. You may consider those access of contract is an attempt of Hacking activity.

Here is the sample code as below.

```cpp
void transfer(uint64_t sender, uint64_t receiver) {

  ...

  auto tx_size = transaction_size();

  char tx[tx_size];

  auto read_size = read_transaction(tx, tx_size);

  eosio_assert( tx_size == read_size, "read_transaction failed");

  auto trx = eosio::unpack<eosio::transaction>( tx, read_size );

  eosio::action first_action = trx.actions.front();

  std::string action_name = name_to_string(first_action.name);

//if (first_action.name != N(transfer) && first_action.account != N(eosio.token)) { 
 if (first_action.name != N(transfer) || first_action.account != N(eosio.token)) {
      return; //or assert
    }
}
```
In [this transaction](https://eosflare.io/tx/c23956381f3925fcd147c3d62eb41ef06461a595401026debc131f83ae10f215), the hacker attempts to hack, in which case the value of `first_action.name` in the above code becomes `deal`. and `first_action.account` is `1supereosman`.
The thing to note here is that you have to compare account and action together.

If you like my idea, please refer to our site on your SNS or site. (https://eosgameboy.io)

Your friend.

**Comment by eoswindev** [comment]
Hey gay, thank you for the advise.Some friend also suggest it

**Comment by eoswindev** [comment]
Hello friend, thank you for your advise. Some other friend also suggests it!

**Comment by chesterchen2010** [comment]
what if hacking in the second action?
